# start from the rocker/r-ver:3.6.3 image
FROM rocker/r-ver:3.6.3

# install the linux libraries needed for plumber
RUN apt-get update -qq && apt-get install -y \
  libssl-dev \
  libcurl4-gnutls-dev \
  libudunits2-dev \
  libgdal-dev \
  libgeos-dev \
  libproj-dev \
  libfontconfig1-dev

# install plumber
RUN R -e "install.packages(c('tidyr','dplyr','sf','tidycensus','future','plumber'))"

# copy everything from the current directory into the container
COPY / /

# open port 80 to traffic
EXPOSE 80

# when the container starts, start the main.R script
ENTRYPOINT ["Rscript", "main.R"]
